DROP TABLE IF EXISTS online_news_popularity;

CREATE TABLE online_news_popularity (
    url TEXT,
    timedelta DOUBLE PRECISION,
    n_tokens_title DOUBLE PRECISION,
    n_tokens_content DOUBLE PRECISION,
    n_unique_tokens DOUBLE PRECISION,
    n_non_stop_words DOUBLE PRECISION,
    n_non_stop_unique_tokens DOUBLE PRECISION,

    num_hrefs DOUBLE PRECISION,
    num_self_hrefs DOUBLE PRECISION,
    num_imgs DOUBLE PRECISION,
    num_videos DOUBLE PRECISION,
    average_token_length DOUBLE PRECISION,
    num_keywords DOUBLE PRECISION,
    data_channel_is_lifestyle DOUBLE PRECISION,
    data_channel_is_entertainment DOUBLE PRECISION,
    data_channel_is_bus DOUBLE PRECISION,
    data_channel_is_socmed DOUBLE PRECISION,
    data_channel_is_tech DOUBLE PRECISION,
    data_channel_is_world DOUBLE PRECISION,
    kw_min_min DOUBLE PRECISION,
    kw_max_min DOUBLE PRECISION,
    kw_avg_min DOUBLE PRECISION,
    kw_min_max DOUBLE PRECISION,
    kw_max_max DOUBLE PRECISION,
    kw_avg_max DOUBLE PRECISION,
    kw_min_avg DOUBLE PRECISION,
    kw_max_avg DOUBLE PRECISION,
    kw_avg_avg DOUBLE PRECISION,
    self_reference_min_shares DOUBLE PRECISION,
    self_reference_max_shares DOUBLE PRECISION,
    self_reference_avg_sharess DOUBLE PRECISION,
    weekday_is_monday DOUBLE PRECISION,
    weekday_is_tuesday DOUBLE PRECISION,
    weekday_is_wednesday DOUBLE PRECISION,
    weekday_is_thursday DOUBLE PRECISION,
    weekday_is_friday DOUBLE PRECISION,
    weekday_is_saturday DOUBLE PRECISION,
    weekday_is_sunday DOUBLE PRECISION,
    is_weekend DOUBLE PRECISION,
    LDA_00 DOUBLE PRECISION,
    LDA_01 DOUBLE PRECISION,
    LDA_02 DOUBLE PRECISION,
    LDA_03 DOUBLE PRECISION,
    LDA_04 DOUBLE PRECISION,
    global_subjectivity DOUBLE PRECISION,
    global_sentiment_polarity DOUBLE PRECISION,
    global_rate_positive_words DOUBLE PRECISION,
    global_rate_negative_words DOUBLE PRECISION,
    rate_positive_words DOUBLE PRECISION,
    rate_negative_words DOUBLE PRECISION,
    avg_positive_polarity DOUBLE PRECISION,
    min_positive_polarity DOUBLE PRECISION,
    max_positive_polarity DOUBLE PRECISION,
    avg_negative_polarity DOUBLE PRECISION,
    min_negative_polarity DOUBLE PRECISION,
    max_negative_polarity DOUBLE PRECISION,
    title_subjectivity DOUBLE PRECISION,
    title_sentiment_polarity DOUBLE PRECISION,
    abs_title_subjectivity DOUBLE PRECISION,
    abs_title_sentiment_polarity DOUBLE PRECISION,
    shares DOUBLE PRECISION
);

COPY online_news_popularity
FROM 'D:/Pranshu/Projects/DBT_Tool_Practice/Data/Cleaned_data/cleaned.csv'
DELIMITER ','
CSV HEADER;